version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    environment:
      DBHOST: postgres
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres-data: