#Utilisation de l'image postgres, version 15
FROM postgres:15

#copie des fichiers init.sql (dump local de la base)
#postgresql.conf (fichier de configuration) vers les répertoires dédiés du container.
COPY ./server/init.sql /docker-entrypoint-initdb.d/
COPY ./server/postgresql.conf /etc/postgresql/postgresql.conf

#exécution des commandes suivantes lors du build
CMD ["postgres","-c", "config_file=/etc/postgresql/postgresql.conf"]