FROM postgres:15

COPY ./server/init.sql /docker-entrypoint-initdb.d/
COPY ./server/postgresql.conf /etc/postgresql/postgresql.conf

CMD ["postgres","-c", "config_file=/etc/postgresql/postgresql.conf"]