name: Site Web Laure CI/CD pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: [main]
  workflow_dispatch:


env:
  POSTGRES_DB: ${DBNAME}
  POSTGRES_USER: ${DBUSER}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  NODE_ENV: test

jobs:

  #tests

  build:
    #needs: tests

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3

      #login to docker hub
      - name: sitepoterielaure
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}


      #build and push server image
      - name: Build and push server image
        uses: docker/build-push-action@v4
        with: 
          context: ./server
          push: true
          tags: thomassaiag/siteweblaure-server:latest

      #build and push client image
      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: thomassaiag/sitweblaure-client:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref=='refs/heads/main'

    steps:
      # Install sshpass
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
      

      #Add Server to known hosts
      - name: Add Server to known hosts
        run: ssh-keyscan -H 188.165.238.74 >> ~/.ssh/known_hosts

      #login to Docker Hub from Server
      - name: Docker Login from Server
        env: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no debian@188.165.238.74 \
          "echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin"

      # Pull and run Docker images
      - name: Deploy with Docker
        env: 
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no debian@188.165.238.74 \
          "docker pull thomassaiag/siteweblaure-server:latest && \
          docker pull thomassaiag/siteweblaure-client:latest && \
          docker stop siteweblaure-server || true && \
          docker stop siteweblaure-client || true && \
          docker rm siteweblaure-server || true && \
          docker rm siteweblaure-client || true && \
          docker run -d --name siteweblaure-server -p 14001:14001 -e NODE_ENV=production thomassaiag/siteweblaure-server:latest && \
          docker run -d --name siteweblaure-client -p 14000:14000 thomassaiag/siteweblaure-client:latest"